name: english_geni
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# major, minor, and patch parts + build-number
version: 1.0.0+1
environment:
  sdk: ^3.12.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  get_storage: ^2.1.1
  flutter_secure_storage: ^10.3.1
  flutter_localization: ^0.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/
  fonts:
    # 1. Your Headline Font
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900